### ISSUE TITLE
Create CI/CD + add testing packages

### ISSUE THREAD

**Issue by keebrev** [dema-trading-ai/engine#19]
**Create a CI/CD for this engine. Including following tasks:**
- Install testing framework for the engine
- Create test pipeline (on every push)
- Create build pipeline (docker-image, registry push) (on PR to main)
- Connect test-pipeline code analyzing service
- Add PR / Branche protections based on Test pipeline results
- Add badges to README

## Questions:
 **What testing framework could best be used for Python?** 
 **What analyzing services could best be used for code analysis? I only have experience with SonarCloud** 

Possible coding analyzing services:
- SonarCloud
- Codacy (comes with GitHub Apps)

**Comment by pvdklei** [comment]
Travis CI is also an option. It seems more flexible than SonarCloud, as you can just give it a script (f.i. `python -m unittest`) that runs every time a push to github happens, instead of specifying a path to the test files or something similar. It's also free, as opposed to Codacy (if you don't self host).
