### ISSUE TITLE
Add overview of winning days/weeks/months per pair

### ISSUE THREAD

**Issue by DemianVoorhagen6** [dema-trading-ai/engine#200]
Currently we show the total profit per coin (E.G. LTC/USDT 100%, ETH/USDT -30%, etc). It would be nice if we could see something like: Winning weeks: LTC/USDT (40 won/12 lost), ETH/USDT (5 won/47 lost). This might be useful to show losing pairs. We have to discuss what period to do and which implementation, but this is the first concept idea.

**Comment by noudcorten** [comment]
Ok after some thinking I came up with the following:

#### Problem definition
The definition for this problem is: since the beginning of backtesting period, how many weeks have passed and how did the algorithm perform in these weeks on a coin level. Here we track the amount of winning weeks, draw weeks (no profit of loss) and losing weeks. The metric is then displayed in the results overview as (e.g.): 10 / 1 / 6 (W/D/L) .

#### Winning week definition
In my opinion there can be 2 definitions for a winning week:
1. A week is defined as 'winning' when the average profit ratio of that week is >1.
2. A week is defined as 'winning' when the product over all the profit ratios for that week is >1.

#### Implementation
For the implementation we have to track (per coin) the profit ratio per tick. This data is transferred to a dataframe and we use pandas resample() method to resample the used timeframe to a 1 week timeframe. Here we can choose two resampling methods:
1. We start the week at the beginning of the backtesting period
2. We start the week always on a Monday (calendar definition of a week)

**Comment by marijn111** [comment]
Another winning week definition: 

- A coin outperformed the market (profit for a coin is larger than market change)
