### ISSUE TITLE
Poetry as virtual environment instead of Pip

### ISSUE THREAD

**Issue by younessegh** [dema-trading-ai/engine#21]
Reasons:
- Poetry performs its locking significantly faster than pipenv. Because both tools perform file locking after nearly every command, poetry feels snappier in everyday use.

- When removing a dependency, Poetry also uninstalls its sub-dependencies if no other package uses them. Pipenv does not. In this benchmark, for instance, Pipenv orphans 5 dependencies.

- Pipenv has broad support. It is an official project of the Python Packaging Authority, alongside pip. It's also supported by the Heroku Python buildpack, which is useful for anyone with Heroku or Dokku-based deployment strategies (like me).
Poetry is a one-stop shop for dependency management and package management. It simplifies creating a package, managing its dependencies, and publishing it. Compared to Pipenv, Poetry's separate add and install commands are more explicit, and it's faster for everything except for a full dependency install.

- Poetry's version 1.0 is set to address the two areas where I preferred Pipenv: being able to export a requirements.txt file, and being able to avoid installing a package as a dependency of itself.

**Comment by marijn111** [comment]
virtual environments will not be relevant anymore when we switch to a full dockerized setup right? (cc @keebrev)

**Comment by younessegh** [comment]
Also for development? @marijn111

**Comment by dema-trading-ai** [comment]
We can still support it for development. What do you think @marijn111 ?

On the one hand I think Poetry could do no harm, on the other hand I am really wondering what the real con's are.

**Comment by marijn111** [comment]
@younessegh @keebrev We also use pip in our Dockerfile to install our dependencies, so in order to keep consistency its not a good idea to fully switch (also because pip comes preinstalled with Python).
So I think for 'newcomers' let's keep it as simple as possible.

However, for users that are already used to using Poetry and prefer it over docker and pipenv e.g., It might be an idea to add a section to the docs where we explain how to use Poetry to get the engine up and running.

Do you want to tackle that @younessegh ?

**Comment by dema-trading-ai** [comment]
Adding this to the wiki sounds like an idea. cc @WesleyvanDooren

**Comment by younessegh** [comment]
@marijn111 Yes I will

**Comment by sheridavandenbent** [comment]
Closing outdated issue
